### ISSUE TITLE
20级教学大纲与19级教学大纲存在偏差

### ISSUE THREAD

**Issue by NanGuoBean** [hewei2001/HITSZ-OpenCS#40]
![image](https://user-images.githubusercontent.com/71677666/122733101-72ad4580-d2af-11eb-860d-ca25e0565ee1.png)
目前在教务系统上查询的20级大二上开设如图所示。
对比目前仓库，缺少 《软件设计与开发实践A》，以及《汇编语言程序设计》，而新增了原本为大二下的《近世代数》。
目前查询不到20级大二下及之后的培养计划。
请问这方面是否需要根据较小届的教学大纲，每年进行调整？

**Comment by NanGuoBean** [comment]
![image](https://user-images.githubusercontent.com/71677666/122733923-39290a00-d2b0-11eb-90b3-10fabde1b489.png)
附上目前仓库里的目录，作为对比

**Comment by hewei2001** [comment]
关于课改的事情，据我所知每年的课程都会有所微调，有的课程是老师不再开了，也有的是上课学期更改。

如果每次小改动都调整仓库，最后的 history 可能会很臃肿且杂乱（要移动整个文件夹），因此可能未来会在积累了一定的变动后，发布一次大的更新。
