### ISSUE TITLE
关于每一年的 PPT 资料是否应该更新？

### ISSUE THREAD

**Issue by huang-feiyu** [hewei2001/HITSZ-OpenCS#61]
一门课程，同一个老师教学，但是PPT有改善，该如何提交PR？

**Comment by hewei2001** [comment]
我的建议是：请自行甄别「改善」是否大到足以新增一个文件夹。

首先需要明确仓库中课件的作用，我认为是：这些 PPT 可以用于课前浏览预习，而不是做上细致的笔记 or 考前用来复习，这些需求都可以等到老师发最新 PPT 后完成。

基于这个观点，我认为仅当课件发生大幅改变（如从 19 级开始「计算机组成原理」课程加入 RISC-V 内容）时，可以新开一个文件夹存档。

如果你认为这些「改善」虽少但仍有必要，可以在旧文件夹或新文件夹中用一份 readme 说明，而不是上传全部课件。
