### ISSUE TITLE
仓库内容增加

### ISSUE THREAD

**Issue by SoraShu** [hewei2001/HITSZ-OpenCS#65]
是否应增加一些关于创新实验、创新研修相关的内容，主要是一些课程的内容和考核形式，还有一些选课建议。

最近发现新生以及部分大二对这些课程有较大困惑。以及这些课程在教务网上的课程大纲内容都较为简略。

**Comment by hewei2001** [comment]
目前暂时不清楚这方面的需求有多强烈？如果确有必要，可以在根目录下新增一个类似「创新课程」的子目录。

此外，这部分课程的资料收集难度远大于必修课程——选课人数少、课程年年变化、内容繁多.......如果你有这方面的资源，欢迎收集整理贡献！ :grin:
